# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemesSiteBuilder#theme-configuration for an example

name = "Clear"
license = "MIT"
licenselink = "https://github.com/Kepler-69c/clear-hugo-theme/blob/master/LICENSE"
description = "Clear is a minimalist hugo theme."
homepage = "https://github.com/Kepler-69c/clear-hugo-theme"
demosite = ""
tags = ["Hugo", "theme", "blog", "modern", "responsive", "clear", "minimalistic"]
features = ["clean", "gallery", "minimal", "minimalist", "mobile", "personal", "responsive", "simple", "tailwind", "blog", "white"]
min_version = "0.82.0"

[author]
  name = "Kepler-69c"
  homepage = "https://djordjep.tk"
